/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Ruslan Malovsky (https://sketchfab.com/malovsky)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/spaceship-unitron-20a3bf99baf943f2887cb586b5195224
Title: Spaceship Unitron
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Spaceship_Osn_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Spaceship_Turbine_0.geometry} material={materials.Turbine} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
